#!/usr/bin/perl
use strict;
use warnings;
use CGI ':standard';
use DBI;

print "content-type:text/html\n\n";
print "<html><title>Result of the insert operation</title>";

# Connect to the MySQL database
my $dbh = DBI->connect("DBI:mysql:test", "root", "") or die "Could not connect to database: $DBI::errstr";

# Retrieve data from the HTML form
my $fname    = param("fname");
my $lname    = param("lname");
my $age      = param("age");
my $address  = param("address");
my $pincode  = param("pincode");

# Insert data into the 'stud' table
my $insert_query = $dbh->prepare("INSERT INTO stud VALUES (?, ?, ?, ?, ?)");
$insert_query->execute($fname, $lname, $age, $address, $pincode);

# Retrieve and display data from the 'stud' table
my $select_query = $dbh->prepare("SELECT * FROM stud");
$select_query->execute();

print "<table border size=1><tr><th>Firstname</th><th>Last Name</th><th>Age</th><th>Address</th><th>Pincode</th></tr>";

while (my ($fname, $lname, $age, $address, $pincode) = $select_query->fetchrow()) {
  print "<tr><td>$fname</td><td>$lname</td><td>$age</td><td>$address</td><td>$pincode</td></tr>";
}

print "</table>";
$select_query->finish();
$dbh->disconnect();
print "</html>";









<html>
<body>
<form action="http://localhost/cgi-bin/8.pl" method="get">
  First Name: <input type="text" name="fname"> <br>
  Last Name: <input type="text" name="lname"> <br>
  Age: <input type="text" name="age"> <br>
  Address: <input type="text" name="address"> <br>
  Pincode: <input type="text" name="pincode"> <br>
  <input type="submit" value="Submit">
</form>
</body>
</html>
